import type { Metadata } from "next";
import { Geist, Geist_Mono, Afacad } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/theme-provider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const afacad = Afacad({
    variable: "--font-afacad",
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${afacad.variable} antialiased`}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <Toaster
                        className="max-w-sm flex justify-center justify-self-center"
                        toastOptions={{
                            duration: 3000,
                            className:
                                "font-afacad font-bold! sm:text-[calc(1rem-1px)]! mx-auto max-w-sm! w-fit! py-2! px-2.5!",
                        }}
                        expand
                        richColors
                        position="top-center"
                        // visibleToasts={3}
                    />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
